# Generated by Django 5.2.11 on 2026-02-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='is_checked_in',
        ),
    ]
